# Generated by Django 2.2.9 on 2020-01-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='countries',
            new_name='country',
        ),
    ]
